branch-defaults:
  master:
    environment: GriinAPI-dev2
    group_suffix: null
environment-defaults:
  GriinAPI-dev:
    branch: null
    repository: null
  GriinAPI-dev2:
    branch: null
    repository: null
global:
  application_name: GriinAPI
  branch: null
  default_ec2_keyname: evelasquez
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
