# Generated by Django 2.0.4 on 2018-04-23 03:27

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.PositiveSmallIntegerField()),
                ('media', s3direct.fields.S3DirectField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
