# Generated by Django 2.0.4 on 2018-04-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thrive',
            old_name='media',
            new_name='story',
        ),
    ]
